// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Done-0/gin-scaffold/configs"
	"github.com/Done-0/gin-scaffold/internal/ai"
	"github.com/Done-0/gin-scaffold/internal/cache"
	"github.com/Done-0/gin-scaffold/internal/db"
	"github.com/Done-0/gin-scaffold/internal/i18n"
	"github.com/Done-0/gin-scaffold/internal/logger"
	"github.com/Done-0/gin-scaffold/internal/queue"
	"github.com/Done-0/gin-scaffold/internal/redis"
	"github.com/Done-0/gin-scaffold/internal/sse"
	"github.com/Done-0/gin-scaffold/internal/torrent"
	"github.com/Done-0/gin-scaffold/pkg/serve/controller"
	"github.com/Done-0/gin-scaffold/pkg/serve/service/impl"
)

// Injectors from wire.go:

// NewContainer initializes the complete application container using Wire
func NewContainer(config *configs.Config) (*Container, error) {
	manager, err := ai.New(config)
	if err != nil {
		return nil, err
	}
	databaseManager := db.New(config)
	redisManager, err := redis.New(config)
	if err != nil {
		return nil, err
	}
	loggerManager, err := logger.New(config)
	if err != nil {
		return nil, err
	}
	cacheManager := cache.New(redisManager, loggerManager)
	i18nManager := i18n.New()
	sseManager := sse.New(config)
	torrentManager, err := torrent.New(config)
	if err != nil {
		return nil, err
	}
	queueProducer, err := queue.NewProducer(config)
	if err != nil {
		return nil, err
	}
	testService := impl.NewTestService(loggerManager, redisManager, manager)
	testController := controller.NewTestController(testService, sseManager)
	torrentService := impl.NewTorrentService(loggerManager, databaseManager, torrentManager, cacheManager)
	torrentController := controller.NewTorrentController(torrentService)
	userService := impl.NewUserService(loggerManager, databaseManager)
	userController := controller.NewUserController(userService)
	adminService := impl.NewAdminService(loggerManager, databaseManager, torrentManager)
	adminController := controller.NewAdminController(adminService)
	transcodeService := impl.NewTranscodeService(config, loggerManager, databaseManager, torrentManager, queueProducer)
	_ = transcodeService // TranscodeService is used by Kafka consumer, not directly by controllers
	container := &Container{
		Config:            config,
		AIManager:         manager,
		CacheManager:      cacheManager,
		DatabaseManager:   databaseManager,
		RedisManager:      redisManager,
		LoggerManager:     loggerManager,
		I18nManager:       i18nManager,
		SSEManager:        sseManager,
		TorrentManager:    torrentManager,
		QueueProducer:     queueProducer,
		TestController:    testController,
		TorrentController: torrentController,
		UserController:    userController,
		AdminController:   adminController,
	}
	return container, nil
}

// wire.go:

// Container holds all application dependencies
type Container struct {
	Config *configs.Config

	// Infrastructure
	AIManager       *ai.AIManager
	CacheManager    cache.CacheManager
	DatabaseManager db.DatabaseManager
	RedisManager    redis.RedisManager
	LoggerManager   logger.LoggerManager
	I18nManager     i18n.I18nManager
	SSEManager      sse.SSEManager
	TorrentManager  torrent.TorrentManager
	QueueProducer   queue.Producer

	// Controllers
	TestController    *controller.TestController
	TorrentController *controller.TorrentController
	UserController    *controller.UserController
	AdminController   *controller.AdminController
}
