// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"magnet2video/configs"
	"magnet2video/internal/ai"
	"magnet2video/internal/cache"
	"magnet2video/internal/cloud"
	"magnet2video/internal/db"
	"magnet2video/internal/i18n"
	"magnet2video/internal/logger"
	"magnet2video/internal/queue"
	"magnet2video/internal/redis"
	"magnet2video/internal/sse"
	"magnet2video/internal/tmdb"
	"magnet2video/internal/torrent"
	"magnet2video/pkg/serve/controller"
	"magnet2video/pkg/serve/service"
	"magnet2video/pkg/serve/service/impl"
)

// Injectors from wire.go:

// NewContainer initializes the complete application container using Wire
func NewContainer(config *configs.Config) (*Container, error) {
	manager, err := ai.New(config)
	if err != nil {
		return nil, err
	}
	redisManager, err := redis.New(config)
	if err != nil {
		return nil, err
	}
	loggerManager, err := logger.New(config)
	if err != nil {
		return nil, err
	}
	cacheManager := cache.New(redisManager, loggerManager)
	cloudStorageManager := cloud.New(config, loggerManager)
	databaseManager := db.New(config)
	i18nManager := i18n.New()
	sseManager := sse.New(config)
	torrentManager, err := torrent.New(config)
	if err != nil {
		return nil, err
	}
	producer, err := queue.NewProducer(config)
	if err != nil {
		return nil, err
	}
	tmdbClient := tmdb.New(config)
	testService := impl.NewTestService(loggerManager, redisManager, manager)
	testController := controller.NewTestController(testService, sseManager)
	torrentServiceImpl := impl.NewTorrentService(loggerManager, databaseManager, torrentManager, cacheManager)
	torrentController := controller.NewTorrentController(config, torrentServiceImpl, databaseManager, cloudStorageManager, producer, tmdbClient)
	userService := impl.NewUserService(loggerManager, databaseManager)
	userController := controller.NewUserController(userService)
	adminService := impl.NewAdminService(loggerManager, databaseManager, torrentManager)
	adminController := controller.NewAdminController(adminService)
	transcodeServiceImpl := impl.NewTranscodeService(config, loggerManager, databaseManager, torrentManager, producer)
	container := &Container{
		Config:              config,
		AIManager:           manager,
		CacheManager:        cacheManager,
		CloudStorageManager: cloudStorageManager,
		DatabaseManager:     databaseManager,
		RedisManager:        redisManager,
		LoggerManager:       loggerManager,
		I18nManager:         i18nManager,
		SSEManager:          sseManager,
		TorrentManager:      torrentManager,
		QueueProducer:       producer,
		TMDBClient:          tmdbClient,
		TestController:      testController,
		TorrentController:   torrentController,
		UserController:      userController,
		AdminController:     adminController,
		TorrentService:      torrentServiceImpl,
		TranscodeService:    transcodeServiceImpl,
	}
	return container, nil
}

// wire.go:

// Container holds all application dependencies
type Container struct {
	Config *configs.Config

	// Infrastructure
	AIManager           *ai.AIManager
	CacheManager        cache.CacheManager
	CloudStorageManager cloud.CloudStorageManager
	DatabaseManager     db.DatabaseManager
	RedisManager        redis.RedisManager
	LoggerManager       logger.LoggerManager
	I18nManager         i18n.I18nManager
	SSEManager          sse.SSEManager
	TorrentManager      torrent.TorrentManager
	QueueProducer       queue.Producer
	TMDBClient          *tmdb.TMDBClient

	// Controllers
	TestController    *controller.TestController
	TorrentController *controller.TorrentController
	UserController    *controller.UserController
	AdminController   *controller.AdminController

	// Services
	TorrentService   service.TorrentService
	TranscodeService service.TranscodeService
}
