// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Done-0/gin-scaffold/configs"
	"github.com/Done-0/gin-scaffold/internal/ai"
	"github.com/Done-0/gin-scaffold/internal/db"
	"github.com/Done-0/gin-scaffold/internal/i18n"
	"github.com/Done-0/gin-scaffold/internal/logger"
	"github.com/Done-0/gin-scaffold/internal/redis"
	"github.com/Done-0/gin-scaffold/internal/sse"
	"github.com/Done-0/gin-scaffold/internal/torrent"
	"github.com/Done-0/gin-scaffold/pkg/serve/controller"
	"github.com/Done-0/gin-scaffold/pkg/serve/service/impl"
)

// Injectors from wire.go:

// NewContainer initializes the complete application container using Wire
func NewContainer(config *configs.Config) (*Container, error) {
	manager, err := ai.New(config)
	if err != nil {
		return nil, err
	}
	databaseManager := db.New(config)
	redisManager, err := redis.New(config)
	if err != nil {
		return nil, err
	}
	loggerManager, err := logger.New(config)
	if err != nil {
		return nil, err
	}
	i18nManager := i18n.New()
	sseManager := sse.New(config)
	torrentManager, err := torrent.New(config)
	if err != nil {
		return nil, err
	}
	testService := impl.NewTestService(loggerManager, redisManager, manager)
	testController := controller.NewTestController(testService, sseManager)
	torrentService := impl.NewTorrentService(loggerManager, databaseManager, torrentManager)
	torrentController := controller.NewTorrentController(torrentService)
	userService := impl.NewUserService(loggerManager, databaseManager)
	userController := controller.NewUserController(userService)
	container := &Container{
		Config:            config,
		AIManager:         manager,
		DatabaseManager:   databaseManager,
		RedisManager:      redisManager,
		LoggerManager:     loggerManager,
		I18nManager:       i18nManager,
		SSEManager:        sseManager,
		TorrentManager:    torrentManager,
		TestController:    testController,
		TorrentController: torrentController,
		UserController:    userController,
	}
	return container, nil
}

// wire.go:

// Container holds all application dependencies
type Container struct {
	Config *configs.Config

	// Infrastructure
	AIManager       *ai.AIManager
	DatabaseManager db.DatabaseManager
	RedisManager    redis.RedisManager
	LoggerManager   logger.LoggerManager
	I18nManager     i18n.I18nManager
	SSEManager      sse.SSEManager
	TorrentManager  torrent.TorrentManager

	// Controllers
	TestController    *controller.TestController
	TorrentController *controller.TorrentController
	UserController    *controller.UserController
}
