import Navbar from './component/Navbar/Navbar'
import Footer from './component/Footer/Footer'
import AuthProvider from './component/AuthProvider/AuthProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from './context/ThemeContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
            <AuthProvider>
              <div className="container">
                <Navbar/>
                  {children}
                <Footer/>
              </div>
            </AuthProvider>
        </ThemeProvider>      
      </body>
    </html>
  )
}
